<?php

$lang = [
    //is hoofdletter gevoelig
    '2nd chance auctions'=>'2e kans veilingen',
    'Categories'=>'Categorieën',
    'Languages'=>'Talen',
    'Items'=>'Artikelen',
    'View Favorites'=>'Favorieten bekijken',
    'login'=>'Inloggen',
    'Profile'=>'Profiel',
    'Settings'=>'Instellingen',
    'Add Product'=>'Product toevoegen',
    'Logout'=>'Afmelden',
    'Register'=>'Registreer',
    'First name'=>'Voornaam',
    'Last name'=>'Achternaam',
    'Email'=>'E-mail',
    'Password'=>'Wachtwoord',
    'password'=>'Wachtwoord',
    'Description'=>'Beschrijving',
    'Profile Picture'=>'Profielfoto',
    'Product'=>'Product',
    'I have an account'=>'Ik heb een account',
    "I don't have an account"=>'Ik heb geen account',
    'Change user'=>'Gebruiker wijzigen',
    'Update information'=>'Informatie bijwerken',
    'Change'=>'wijzigen',
    'invoice'=>'factuur',
    'Overview of auctions'=>'Overzicht van veilingen',
    'Minimum price'=>'Minimale prijs',
    'Product Picture'=>'Productfoto',
    'Category'=>'Categorie',
    'Choose a category'=>'Kies een categorie',
    'ADD PRODUCT'=>'PRODUCT TOEVOEGEN',
    'Search'=>'Zoeken',
    'How long should your auction last'=>'Hoelang moet je veiling duren',
    'Favorites'=>'Favorieten',
    'Add favorites to your list to view'=>'Voeg favorieten toe aan uw lijst om te bekijken',
    "hours"=>'uur',
    'Document'=>'Document',
    'Highest offer'=>'Hoogste bod',
    'Time left'=>'Tijd over',
    'Purchase History'=>'Aankoop geschiedenis',
    'Sales'=>'Verkoop',
    'Revenue'=>'Winst',
    'Total amount of money brought in'=>'Totaal binnengebracht geldbedrag',
    'Active products'=>'Actieve producten',
    'Products sold'=>'Producten verkocht',
    'Overview of all active products'=>'Overzicht van alle actieve producten',
    'Purchases'=>'Aankopen',
    'Expenses'=>'Uitgaven',
    'Total amount of money spent'=>'Totaal uitgegeven geldbedrag',
    'Products bought'=>'Producten gekocht',
    'Your sales'=>'Jouw omzet',
    'Name'=>'Naam',
    'Price'=>'Prijs',
    'Date'=>'Datum',
    'See all sales'=>'Bekijk alle verkopen',
    'Your purchases'=>'Uw aankopen',
    'See all purchases'=>'Bekijk alle aankopen',
    'Warning!'=> 'waarschuwing!',
    'Someone ourtbid you'=> 'Iemand heeft een hoger bod dan jouw',
    'see'=> 'zien'
];

?>