<?php

$lang = [
    //is hoofdletter gevoelig
    '2nd chance auctions'=>'2e kans veilingen',
    'Categories'=>'Categorieën',
    'Languages'=>'Talen',
    'Items'=>'Artikelen',
    'View Favorites'=>'Favorieten bekijken',
    'login'=>'Inloggen',
    'Profile'=>'Profiel',
    'Settings'=>'Instellingen',
    'Add Product'=>'Product toevoegen',
    'Logout'=>'Afmelden',
    'Register'=>'Registreer',
    'First name'=>'Voornaam',
    'Last name'=>'Achternaam',
    'Email'=>'E-mail',
    'Password'=>'Wachtwoord',
    'password'=>'Wachtwoord',
    'Description'=>'Beschrijving',
    'Profile Picture'=>'Profielfoto',
    'Product'=>'Product',
    'I have an account'=>'Ik heb een account',
    "I don't have an account"=>'Ik heb geen account',
    'Change user'=>'Gebruiker wijzigen',
    'Update information'=>'Informatie bijwerken',
    'Change'=>'wijzigen',
    'invoice'=>'factuur',
    'Overview of auctions'=>'Overzicht van veilingen',
    'Minimum price'=>'Minimale prijs',
    'Product Picture'=>'Productfoto',
    'Category'=>'Categorie',
    'Choose a category'=>'Kies een categorie',
    'ADD PRODUCT'=>'PRODUCT TOEVOEGEN',
    'Search'=>'Zoeken',
    'How long should your auction last'=>'Hoelang moet je veiling duren',
    'Favorites'=>'Favorieten',
    'Add favorites to your list to view'=>'Voeg favorieten toe aan uw lijst om te bekijken',
    "hours"=>'uur',
    'Update information'=>'Update informatie',
    'Document'=>'Document',
    'Highest offer'=>'Hoogste bod',
    'Time left'=>'Tijd over',
    'Purchase History'=>'Aankoop geschiedenis'
];

?>